name: 'Example (Specify: project-owner, project-number, issue-repository, issue-number)'
on:
  workflow_dispatch:
    inputs:
      project-owner:
        default: ''
        required: true
        description: 'User/Organization name project contains.'
      project-owner-type:
        default: 'organization'
        required: true
        description: 'Type of owner of project: User, Organization'
      project-number:
        default: 0
        required: true
        description: 'The number of the target project.'
      issue-repository:
        default: ''
        required: true
        description: 'Repository name with owner of issue.'
      issue-number:
        default: 0
        required: true
        description: 'Number of issue.'

jobs:
  example:
    name: Example job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Project Item Id
      id: get-project-item-id
      uses: ./
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        project-owner: ${{ github.event.inputs.project-owner }}
        project-owner-type: ${{ github.event.inputs.project-owner-type }}
        project-number: ${{ github.event.inputs.project-number }}
        issue-repository: ${{ github.event.inputs.issue-repository }}
        issue-number: ${{ github.event.inputs.issue-number }}
    - name: Output result
      run: |
        echo '${{ steps.get-project-item-id.outputs.project-item-id }}'
