name: Tests on Push
on:
  push:
    branches:
      - main
      - develop
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
